

- name: add repositories
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - python-mysqldb

- name: start always mysql
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install mysql extension for php
  apt: name = {{item}} state:present
  with_items:
    - php5-mysql

- name: Create database
  mysql_db: name={{nomdb}} state=present collation=utf8_general_ci

- name: Create User DB
  mysql_user: name={{ myname }} password={{ mypass }} priv=*.*:ALL host='%' state=present
